-- INSERT INTO movies (movie_name,movie_rated,duration ) VALUES ('The Shawshank Redemption','R',142);
-- INSERT INTO movies (movie_name,movie_rated,duration ) VALUES ('The Usual Suspects','R',106);
-- INSERT INTO movies(movie_name,movie_rated,duration  ) VALUES ('Papillon','R',151);
-- INSERT INTO movies (movie_name,movie_rated,duration ) VALUES ('The Terminator','R',107);